### ISSUE TITLE
Complex types lab is missing

### ISSUE THREAD

**Issue by ylashin** [databricks-academy/apache-spark-programming-with-databricks#1]
Hi,

The lab for complex types seems to be missing (unless it is located in some other folder)

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2197158/153330176-1e2a363c-02ae-4465-ac6d-90d11350964f.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/2197158/153330427-9ea1edbe-7dad-4564-aadc-96676039942b.png">

**Comment by SireInsectus** [comment]
This has been moved to our backlog
