### ISSUE TITLE
Course lab mismatch

### ISSUE THREAD

**Issue by dkvaravo** [databricks-academy/apache-spark-programming-with-databricks#2]
In the [Apache Spark Programming - Dataframes](https://customer-academy.databricks.com/learn/course/63/play/3894:610/dataframes;lp=10) case study the instructor is showing a notebook called `ASP 1.2 Databricks platform` which is not found in this repo (at least not under this name), is the repo and the course materials synced?

`ASP 1.3 Spark SQL` is also missing in the repo, as well as `ASP 1.4` and `ASP 1.5`

**Comment by SireInsectus** [comment]
We have moved this to our backlog
